In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

In [ ]:
df=pd.read_csv('../input/states_all.csv')

In [ ]:
df.head(2)

In [ ]:
education2_df = df.copy()

fill_list = ["ENROLL", "TOTAL_REVENUE", "FEDERAL_REVENUE", 
             "STATE_REVENUE", "LOCAL_REVENUE", "TOTAL_EXPENDITURE", 
             "INSTRUCTION_EXPENDITURE", "SUPPORT_SERVICES_EXPENDITURE",
             "OTHER_EXPENDITURE", "CAPITAL_OUTLAY_EXPENDITURE", "GRADES_PK_G", 
             "GRADES_KG_G", "GRADES_4_G", "GRADES_8_G", "GRADES_12_G", "GRADES_1_8_G", 
             "GRADES_9_12_G", "GRADES_ALL_G"]

for col in fill_list:
    education2_df.loc[:, col].fillna(education2_df.loc[:, col].mean(), inplace=True)

In [51]:
education3_df = df.copy()

years = education3_df["YEAR"].unique() 

for col in fill_list:
    for year in years: 
        if len(education3_df.loc[education3_df["YEAR"] == year][col].unique())==1: 
            #col value is all null for that year, then fill it with 0 
            education3_df.loc[education3_df["YEAR"] == year,  col]= \
            education3_df.loc[education3_df["YEAR"] == year,  col].fillna(0)
        else: 
            education3_df.loc[education3_df["YEAR"] == year,  col] = \
            education3_df.loc[education3_df["YEAR"] == year, col].fillna(education3_df[(education3_df["YEAR"] == year) & \
              (education3_df[col].isnull()==False) ][col].mean())

In [52]:
education3_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1492 entries, 0 to 1491
Data columns (total 25 columns):
PRIMARY_KEY                     1492 non-null object
STATE                           1492 non-null object
YEAR                            1492 non-null int64
ENROLL                          1492 non-null float64
TOTAL_REVENUE                   1492 non-null float64
FEDERAL_REVENUE                 1492 non-null float64
STATE_REVENUE                   1492 non-null float64
LOCAL_REVENUE                   1492 non-null float64
TOTAL_EXPENDITURE               1492 non-null float64
INSTRUCTION_EXPENDITURE         1492 non-null float64
SUPPORT_SERVICES_EXPENDITURE    1492 non-null float64
OTHER_EXPENDITURE               1492 non-null float64
CAPITAL_OUTLAY_EXPENDITURE      1492 non-null float64
GRADES_PK_G                     1492 non-null float64
GRADES_KG_G                     1492 non-null float64
GRADES_4_G                      1492 non-null float64
GRADES_8_G                      1492 non-null float64
GRADES_12_G                     1492 non-null float64
GRADES_1_8_G                    1492 non-null float64
GRADES_9_12_G                   1492 non-null float64
GRADES_ALL_G                    1492 non-null float64
AVG_MATH_4_SCORE                536 non-null float64
AVG_MATH_8_SCORE                532 non-null float64
AVG_READING_4_SCORE             533 non-null float64
AVG_READING_8_SCORE             498 non-null float64
dtypes: float64(22), int64(1), object(2)
memory usage: 291.5+ KB

In [54]:
education3_df.head(100)

                  PRIMARY_KEY         ...         AVG_READING_8_SCORE
0                1992_ALABAMA         ...                         NaN
1                 1992_ALASKA         ...                  258.859712
2                1992_ARIZONA         ...                  262.169895
3               1992_ARKANSAS         ...                  264.619665
4             1992_CALIFORNIA         ...                         NaN
5               1992_COLORADO         ...                  266.419687
6            1992_CONNECTICUT         ...                  264.713904
7               1992_DELAWARE         ...                  261.577921
8   1992_DISTRICT_OF_COLUMBIA         ...                  265.976765
9                1992_FLORIDA         ...                  262.118986
10               1992_GEORGIA         ...                         NaN
11                1992_HAWAII         ...                         NaN
12                 1992_IDAHO         ...                         NaN
13              1992_ILLINOIS         ...                         NaN
14               1992_INDIANA         ...                         NaN
15                  1992_IOWA         ...                         NaN
16                1992_KANSAS         ...                         NaN
17              1992_KENTUCKY         ...                         NaN
18             1992_LOUISIANA         ...                         NaN
19                 1992_MAINE         ...                         NaN
20              1992_MARYLAND         ...                         NaN
21         1992_MASSACHUSETTS         ...                         NaN
22              1992_MICHIGAN         ...                         NaN
23             1992_MINNESOTA         ...                         NaN
24           1992_MISSISSIPPI         ...                         NaN
25              1992_MISSOURI         ...                         NaN
26               1992_MONTANA         ...                         NaN
27              1992_NEBRASKA         ...                         NaN
28                1992_NEVADA         ...                         NaN
29         1992_NEW_HAMPSHIRE         ...                         NaN
..                        ...         ...                         ...
70                 1993_MAINE         ...                         NaN
71              1993_MARYLAND         ...                         NaN
72         1993_MASSACHUSETTS         ...                         NaN
73              1993_MICHIGAN         ...                         NaN
74             1993_MINNESOTA         ...                         NaN
75           1993_MISSISSIPPI         ...                         NaN
76              1993_MISSOURI         ...                         NaN
77               1993_MONTANA         ...                         NaN
78              1993_NEBRASKA         ...                         NaN
79                1993_NEVADA         ...                         NaN
80         1993_NEW_HAMPSHIRE         ...                         NaN
81            1993_NEW_JERSEY         ...                         NaN
82            1993_NEW_MEXICO         ...                         NaN
83              1993_NEW_YORK         ...                         NaN
84        1993_NORTH_CAROLINA         ...                         NaN
85          1993_NORTH_DAKOTA         ...                         NaN
86                  1993_OHIO         ...                         NaN
87              1993_OKLAHOMA         ...                         NaN
88                1993_OREGON         ...                         NaN
89          1993_PENNSYLVANIA         ...                         NaN
90          1993_RHODE_ISLAND         ...                         NaN
91        1993_SOUTH_CAROLINA         ...                         NaN
92          1993_SOUTH_DAKOTA         ...                         NaN
93             1993_TENNESSEE         ...                         NaN
94                 1993_TEXAS         ...                         NaN
95                  1993_UTAH         ...                         NaN
96               1993_VERMONT         ...                         NaN
97              1993_VIRGINIA         ...                         NaN
98            1993_WASHINGTON         ...                         NaN
99         1993_WEST_VIRGINIA         ...                         NaN

[100 rows x 25 columns]